# Generated by Django 3.1.2 on 2020-11-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_pago',
        ),
    ]
