# Generated by Django 3.1.2 on 2020-10-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20201026_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Eliminado', 'Eliminado'), ('Creado', 'Creado'), ('Pago', 'Pago'), ('En Preparacion', 'En Preparacion'), ('Preparado', 'Preparado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Creado', max_length=50),
        ),
    ]
