# Generated by Django 3.1.2 on 2020-11-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0003_auto_20201030_0225'),
        ('pedidos', '0004_auto_20201026_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direcciones.direccion'),
        ),
    ]
