# Generated by Django 3.1.2 on 2020-11-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_direccion_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Eliminado', 'Eliminado'), ('Creado', 'Creado'), ('Cancelado', 'Cancelado'), ('Pago', 'Pago'), ('En Preparacion', 'En Preparacion'), ('Preparado', 'Preparado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Creado', max_length=50),
        ),
    ]
