# Generated by Django 3.1.2 on 2020-11-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
        ('pedidos', '0006_auto_20201115_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarjetas.tarjeta'),
        ),
    ]
