# Generated by Django 3.1.2 on 2020-11-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
        ('pedidos', '0007_pedido_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cupones.cupon'),
        ),
    ]
