# Generated by Django 3.1.2 on 2020-12-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20201129_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(null=True),
        ),
    ]
