# Generated by Django 3.1.2 on 2020-10-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='prinicipal',
            new_name='principal',
        ),
    ]
