# Generated by Django 3.1.2 on 2020-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_auto_20201030_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='numero_calle',
            field=models.IntegerField(),
        ),
    ]
