# Generated by Django 3.1.2 on 2020-11-16 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarjeta', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('empresa', models.CharField(max_length=50)),
                ('fondos', models.CharField(max_length=50)),
                ('principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
