# Generated by Django 3.1.2 on 2020-11-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
